name: ws-base CI

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-20.04
        if: github.repository == 'PhantomOfLINUX/Agent'
        steps:
            - name: git code checkout
              uses: actions/checkout@v3

            - name: docker setup
              uses: docker/setup-buildx-action@v3

            - name: docker login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Load Image Version and Check Latest
              id: version
              run: |
                  VERSION=$(jq -r .now_version image_tag.config.json)
                  LATEST=$(jq -r .latest image_tag.config.json)
                  TAGS="${{ secrets.DOCKERHUB_ORGANIZATIONS }}/ws-base:$VERSION"
                  if [ "$LATEST" = "true" ]; then
                    TAGS="$TAGS,${{ secrets.DOCKERHUB_ORGANIZATIONS }}/ws-base:latest"
                  fi
                  echo "TAGS=$TAGS" >> $GITHUB_ENV

            - name: Build and Push Image
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./ws-base.Dockerfile
                  push: true
                  tags: ${{ env.TAGS }}
                  cache-from: type=registry,ref=${{ secrets.DOCKERHUB_ORGANIZATIONS }}/ws-base:cache
                  cache-to: type=inline
